<div class="presented-response-container ng-tns-c410382547-80" _ngcontent-ng-c410382547="">
    <div class="response-container-content ng-tns-c410382547-80 tunable-selection-with-avatar" _ngcontent-ng-c410382547="" selection="">
        <div class="response-content ng-tns-c410382547-80" _ngcontent-ng-c2337681859="">
            <div class="markdown markdown-main-panel" dir="ltr" _ngcontent-ng-c2474201552="">
                <p data-sourcepos="3:1-3:46"><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://panchhipetha.com/collections/petha" data-mce-href="https://panchhipetha.com/collections/petha" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Panchhi Petha logo" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRM6L0k1oJnNc-STINGsqkw59zgWskZmPC1-gxlbpOYuiznfIAG_su_8zVR3ShE" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRM6L0k1oJnNc-STINGsqkw59zgWskZmPC1-gxlbpOYuiznfIAG_su_8zVR3ShE" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""> </span></a></p>
                <p data-sourcepos="6:1-6:87"><span data-state="closed" aria-controls="radix-:r8:" aria-expanded="false" aria-haspopup="dialog" type="button" class="cursor-pointer whitespace-pre-line text-base font-normal text-title-color  transition-opacity duration-150 hover:bg-gray-200">Panchhi Petha is the name that has been the pioneer in the field of Indian Sweets and has been serving petha lover for many years now. </span><span data-state="closed" aria-controls="radix-:r9:" aria-expanded="false" aria-haspopup="dialog" type="button" class="cursor-pointer whitespace-pre-line text-base font-normal text-title-color  transition-opacity duration-150 hover:bg-gray-200">Originally located in the city of Agra, Panchhi Petha is now associated with unimaginable quality, completely genuine taste and a vast product range.</span></p>
                <h3 data-sourcepos="8:1-9:35">Varieties of Petha at Panchhi Petha</h3>
                <div class="attachment-container search-images">
                    <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                        <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><span>Panchhi Petha provides a large array of petha types each with its own special taste and feel. Here are some of the most liked types: </span></div>
                    </div>
                </div>
                <ul data-sourcepos="13:1-19:62">
                    <li data-sourcepos="13:1-15:0"><strong>Plain Petha:</strong><span> The classic petha made with pure ash gourd and sugar, is a soft see-through treat that dissolves in your mouth.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://panchhipetha.com/products/plain-petha" data-mce-href="https://panchhipetha.com/products/plain-petha" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Plain Petha" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRzAv4TjWRYJEm1Pxctg9M-JDNHGrAeaCkj3MXjxnpG283bnfVtZqX9evSxy-Bj" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRzAv4TjWRYJEm1Pxctg9M-JDNHGrAeaCkj3MXjxnpG283bnfVtZqX9evSxy-Bj" _ngcontent-ng-c3975567433=""></span></a>&nbsp;</div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="16:1-18:0"><strong>Kesar Petha:</strong><span> With a scent as well as colour similar to saffron, Kesar Petha is a costly range which provides a taste of luxury.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://panchhipetha.com/products/kesar-angoori-petha" data-mce-href="https://panchhipetha.com/products/kesar-angoori-petha" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Kesar Petha" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwtIPZgo6JeJ3g0UfegxmgOlGAaRFuuUdmm58FG41wz9eXP9tYjS1Bv4-QuHyN" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwtIPZgo6JeJ3g0UfegxmgOlGAaRFuuUdmm58FG41wz9eXP9tYjS1Bv4-QuHyN" _ngcontent-ng-c3975567433=""></span></a>&nbsp;</div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="19:1-19:62"><strong>Angoori Petha:</strong><span> Cunningly packaged like small grapes, Angoori Petha refers to the petha sweets that are a fusion of the sweetness of petha and a grape-like zesty flavor.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://m.indiamart.com/proddetail/kesar-petha-19370552330.html" data-mce-href="https://m.indiamart.com/proddetail/kesar-petha-19370552330.html" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Angoori Petha" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTGdsd5iny6UkeWx37LIhw_yb870qkm3czhrj2wTiwmFUB6GVgIQIJuaMLHN2uF" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTGdsd5iny6UkeWx37LIhw_yb870qkm3czhrj2wTiwmFUB6GVgIQIJuaMLHN2uF" _ngcontent-ng-c3975567433=""></span></a>&nbsp;</div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="22:1-24:0"><strong>Dry Petha:</strong><span> This type of Petha is comparatively healthier than the normal Petha as the petha slices are dried which gives it a chewy feel and apt taste.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://www.amazon.com/Bikano-Dry-Petha/dp/B018VMA84Q" data-mce-href="https://www.amazon.com/Bikano-Dry-Petha/dp/B018VMA84Q" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Dry Petha" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSP6fBr71VPuPDLzyGlW7q_T-j-vBfxDwu6xPsMLcToqv8ayEw9PLBqjyUgFRmw" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSP6fBr71VPuPDLzyGlW7q_T-j-vBfxDwu6xPsMLcToqv8ayEw9PLBqjyUgFRmw" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""></span></a></div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="25:1-27:0"><strong>Pan Petha:</strong><span> A perfect blend of petha and pan, Pan Petha is fresh and a burst of flavors with a cardamom, cloves and fennel after taste.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://theindiasupermart.com/products/paan-petha-gulkhand-roll" data-mce-href="https://theindiasupermart.com/products/paan-petha-gulkhand-roll" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Pan Petha" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSkfHZE5vkK5LpNsuX6RODMcXf7aWB28OqNGYP5FAULGorpj5FVjgy4wE6kRXfg" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSkfHZE5vkK5LpNsuX6RODMcXf7aWB28OqNGYP5FAULGorpj5FVjgy4wE6kRXfg" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""></span></a></div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="28:1-28:74"><strong>Chocolate Petha:</strong><span> Chocolate Petha is the duo of petha and chocolate and its texture is sweet and creamy and it is very delicious to cater your candy desires.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://panchhipetha.com/products/chocolate-petha" data-mce-href="https://panchhipetha.com/products/chocolate-petha" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Chocolate Petha" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRoT0qkqbtTfUUht_vw2GJFzsBXesthnMJVzGYqx_Ys7NsGhmzQnOV7rb6PklyV" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRoT0qkqbtTfUUht_vw2GJFzsBXesthnMJVzGYqx_Ys7NsGhmzQnOV7rb6PklyV" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""></span></a></div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="31:1-33:0"><strong>Melona Petha:</strong><span> Inspired with the aid of the famous ice cream taste, Melona Petha is a light and clean treat with a hint of citrus.</span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://www.amazon.in/PANCHHI-Melon-Petha-Special-Famous/dp/B0BF5RFTQ4" data-mce-href="https://www.amazon.in/PANCHHI-Melon-Petha-Special-Famous/dp/B0BF5RFTQ4" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Melona Petha" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfQfsLFP7bUyaxmXjtqj-FqG_AFwjOS2Li2hzzZuynlw5GVmV_s6h7mAbeMpV-" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfQfsLFP7bUyaxmXjtqj-FqG_AFwjOS2Li2hzzZuynlw5GVmV_s6h7mAbeMpV-" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""></span></a></div>
                            </div>
                        </div>
                    </li>
                    <li data-sourcepos="34:1-36:0"><strong>Gulab Laddu Petha:</strong><span> <span class="cursor-pointer whitespace-pre-line text-base font-normal text-title-color  transition-opacity duration-150 hover:bg-gray-200" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r12:" data-state="closed" data-mce-fragment="1">The newly included in the petha series of tender and soft petha having the touch of sweet and syrupy Gulab Jamun is the sweet combo preparation which is especially known as Gulab Laddu Petha particularly for the feasts.</span><br data-mce-fragment="1"></span>
                        <div class="attachment-container search-images">
                            <div class="image-container hide-from-message-actions ng-star-inserted" _ngcontent-ng-c3975567433="" hide-from-message-actions="">
                                <div class="overlay-container ng-star-inserted" _ngcontent-ng-c3975567433=""><a aria-live="polite" class="image-source-link ng-star-inserted" href="https://panchhipetha.com/products/gulaab-laddu-petha" data-mce-href="https://panchhipetha.com/products/gulaab-laddu-petha" _ngcontent-ng-c3975567433="" target="_blank" externallink="" _nghost-ng-c2698785711="" jslog="181501;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_7714d4dd07d5c9fd&quot;,&quot;c_d59f1e40f413285d&quot;,null,&quot;rc_ad3cc86861a345ef&quot;,null,null,&quot;en&quot;,null,1,null,null,1,0]];mutable:true"><span data-test-id="content" class="ng-star-inserted" _ngcontent-ng-c2698785711=""><img style="display: block; margin-left: auto; margin-right: auto;" class="image loaded" alt="Image of Gulab Laddu Petha" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR5ULToQMO9tngUaGOU3AQ14G_dKYs96GeYyy1l7KQYvrTClJYSAyw-DqFRFqr6" data-mce-style="display: block; margin-left: auto; margin-right: auto;" data-mce-src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR5ULToQMO9tngUaGOU3AQ14G_dKYs96GeYyy1l7KQYvrTClJYSAyw-DqFRFqr6" _ngcontent-ng-c3975567433=""></span><span class="cdk-visually-hidden ng-star-inserted" _ngcontent-ng-c2698785711=""></span></a></div>
                            </div>
                        </div>
                    </li>
                </ul>
                <p data-sourcepos="37:1-37:48"><span data-state="closed" aria-controls="radix-:ro:" aria-expanded="false" aria-haspopup="dialog" type="button" class="cursor-pointer whitespace-pre-line text-base font-normal text-title-color  transition-opacity duration-150 hover:bg-gray-200">The above-mentioned are only few of the numerous petha being served in Panchhi Petha. </span><span data-state="closed" aria-controls="radix-:rp:" aria-expanded="false" aria-haspopup="dialog" type="button" class="cursor-pointer whitespace-pre-line text-base font-normal text-title-color  transition-opacity duration-150 hover:bg-gray-200">As the specialists in quality and novelty Panchhi Petha keeps on enchanting sweet lovers with their fantastic and mouth-watering petha.</span></p>
            </div>
        </div>
    </div>
</div>